version: '3.8'

services:
  db:
    image: postgres:13
    container_name: cubo_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cubo-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: cubo_backend
    volumes:
      - ./back:/var/www/html
    networks:
      - cubo-network
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - cubo-network

  nginx:
    image: nginx:alpine
    container_name: cubo_nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./back/public:/var/www/html
    networks:
      - cubo-network
    depends_on:
      - backend

networks:
  cubo-network:
    driver: bridge

volumes:
  postgres_data:
